### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by AanchalA** [ohmplatform/FreedomGPT#48]
Getting the following error with: `yarn start`

`yarn run v1.22.19
$ electron-forge start
/home/ubuntu/freedom-gpt/node_modules/listr2/dist/index.cjs:90
    this.path = [...task.listr.path ?? [], task.title].join(" > ");
                                     ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/ubuntu/freedom-gpt/node_modules/@electron-forge/cli/dist/electron-forge.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by VickyHax** [comment]
@AanchalA what version of npm are you running? the version windows ubuntu22 wsl installed is 12. 14 is required.
https://github.com/listr2/listr2/issues/661

option 3 via nvm is the classic best way and only method that worked for me: https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04#option-3-installing-node-using-the-node-version-manager
