### ISSUE TITLE
Type 'MakerZIP' is not assignable to type 'ForgeConfigMaker'.

### ISSUE THREAD

**Issue by codeh2o** [ohmplatform/FreedomGPT#58]
after pnpm i ,a error found when run npm start or npm build make-win.

![image](https://user-images.githubusercontent.com/6487457/233817539-d8009386-6801-452f-bdb8-eb7a30eea4d7.png)

```
d:\nodejs\yarn.cmd run start
yarn run v1.22.15
$ electron-forge start
√ Checking your system
√ Locating application
√ Locating application
× Loading configuration
  › ⨯ Unable to compile TypeScript:
  forge.config.ts:51:5 - error TS2322: Type 'MakerZIP' is not assignable to type 'ForgeConfigMaker'.
    Property 'config' is missing in type 'MakerZIP' but required in type 'IForgeResolvableMaker'.
    51     new MakerZIP({}, ["darwin"]),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@electron-forge/shared-types/dist/index.d.ts:109:5
    109     config: any;
            ~~~~~~
    'config' is declared here.
    forge.config.ts:51:18 - error TS2554: Expected 0 arguments, but got 2.
    51     new MakerZIP({}, ["darwin"]),
                        ~~~~~~~~~~~~~~
    forge.config.ts:52:5 - error TS2322: Type 'MakerDMG' is not assignable to type 'ForgeConfigMaker'.
    Property 'config' is missing in type 'MakerDMG' but required in type 'IForgeResolvableMaker'.
    52     new MakerDMG({}, ["darwin"]),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    node_modules/@electron-forge/shared-types/dist/index.d.ts:109:5
    109     config: any;
            ~~~~~~
    'config' is declared here.
    forge.config.ts:52:18 - error TS2554: Expected 0 arguments, but got 2.
    52     new MakerDMG({}, ["darwin"]),
                        ~~~~~~~~~~~~~~
    forge.config.ts:53:5 - error TS2322: Type 'MakerSquirrel' is not assignable to type 'ForgeConfigMaker'.
    Property 'config' is missing in type 'MakerSquirrel' but required in type 'IForgeResolvableMaker'.
     53     new MakerSquirrel(
            ~~~~~~~~~~~~~~~~~~
     54       {
        ~~~~~~~
    ...
     60       ["win32"]
        ~~~~~~~~~~~~~~~
     61     ),
        ~~~~~
    node_modules/@electron-forge/shared-types/dist/index.d.ts:109:5
    109     config: any;
            ~~~~~~
    'config' is declared here.
    forge.config.ts:54:7 - error TS2554: Expected 0 arguments, but got 2.
     54       {
              ~
     55         name: "FreedomGPT",
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...
     59       },
        ~~~~~~~~
     60       ["win32"]
        ~~~~~~~~~~~~~~~
■ Preparing native dependencies
■ Running generateAssets hook

An unhandled rejection has occurred inside Forge:
TSError: ⨯ Unable to compile TypeScript:
forge.config.ts:51:5 - error TS2322: Type 'MakerZIP' is not assignable to type 'ForgeConfigMaker'.
  Property 'config' is missing in type 'MakerZIP' but required in type 'IForgeResolvableMaker'.

51     new MakerZIP({}, ["darwin"]),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@electron-forge/shared-types/dist/index.d.ts:109:5
    109     config: any;
            ~~~~~~
    'config' is declared here.
forge.config.ts:51:18 - error TS2554: Expected 0 arguments, but got 2.

51     new MakerZIP({}, ["darwin"]),
                    ~~~~~~~~~~~~~~
forge.config.ts:52:5 - error TS2322: Type 'MakerDMG' is not assignable to type 'ForgeConfigMaker'.
  Property 'config' is missing in type 'MakerDMG' but required in type 'IForgeResolvableMaker'.

52     new MakerDMG({}, ["darwin"]),
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@electron-forge/shared-types/dist/index.d.ts:109:5
    109     config: any;
            ~~~~~~
    'config' is declared here.
forge.config.ts:52:18 - error TS2554: Expected 0 arguments, but got 2.

52     new MakerDMG({}, ["darwin"]),
                    ~~~~~~~~~~~~~~
forge.config.ts:53:5 - error TS2322: Type 'MakerSquirrel' is not assignable to type 'ForgeConfigMaker'.
  Property 'config' is missing in type 'MakerSquirrel' but required in type 'IForgeResolvableMaker'.

 53     new MakerSquirrel(
        ~~~~~~~~~~~~~~~~~~
 54       {
    ~~~~~~~
...
 60       ["win32"]
    ~~~~~~~~~~~~~~~
 61     ),
    ~~~~~

  node_modules/@electron-forge/shared-types/dist/index.d.ts:109:5
    109     config: any;
            ~~~~~~
    'config' is declared here.
forge.config.ts:54:7 - error TS2554: Expected 0 arguments, but got 2.

 54       {
          ~
 55         name: "FreedomGPT",
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 59       },
    ~~~~~~~~
 60       ["win32"]
    ~~~~~~~~~~~~~~~
at createTSError (E:\web\FreedomGPT\node_modules\.pnpm\ts-node@10.9.1_typescript@4.5.5\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (E:\web\FreedomGPT\node_modules\.pnpm\ts-node@10.9.1_typescript@4.5.5\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (E:\web\FreedomGPT\node_modules\.pnpm\ts-node@10.9.1_typescript@4.5.5\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (E:\web\FreedomGPT\node_modules\.pnpm\ts-node@10.9.1_typescript@4.5.5\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (E:\web\FreedomGPT\node_modules\.pnpm\ts-node@10.9.1_typescript@4.5.5\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (E:\web\FreedomGPT\node_modules\.pnpm\ts-node@10.9.1_typescript@4.5.5\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at exports.default (E:\web\FreedomGPT\node_modules\.pnpm\@electron-forge+core@6.1.1\node_modules\@electron-forge\core\src\util\forge-config.ts:127:22)
    at async Task.task (E:\web\FreedomGPT\node_modules\.pnpm\@electron-forge+core@6.1.1\node_modules\@electron-forge\core\src\api\start.ts:63:29)
    at async Task.run (E:\web\FreedomGPT\node_modules\.pnpm\listr2@5.0.8\node_modules\listr2\dist\index.cjs:978:11)
    at async E:\web\FreedomGPT\node_modules\.pnpm\p-map@4.0.0\node_modules\p-map\index.js:57:22
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1



```

**Comment by maksspace** [comment]
Yep same thing
