### ISSUE TITLE
Module not found: Error: Can't resolve 'bufferutil' in '/home/jet/freedom-gpt/node_modules/ws/lib'

### ISSUE THREAD

**Issue by mmhzlrj** [ohmplatform/FreedomGPT#74]
WARNING in ./node_modules/ws/lib/buffer-util.js 113:23-44
Module not found: Error: Can't resolve 'bufferutil' in '/home/jet/freedom-gpt/node_modules/ws/lib'
 @ ./node_modules/ws/lib/websocket.js 31:21-45
 @ ./node_modules/ws/index.js 3:18-44
 @ ./node_modules/engine.io/build/server.js 12:13-26
 @ ./node_modules/engine.io/build/engine.io.js 5:17-36
 @ ./node_modules/socket.io/dist/index.js 36:20-40
 @ ./src/index.ts 15:20-40

WARNING in ./node_modules/ws/lib/validation.js 117:24-49
Module not found: Error: Can't resolve 'utf-8-validate' in '/home/jet/freedom-gpt/node_modules/ws/lib'
 @ ./node_modules/ws/lib/sender.js 11:30-53
 @ ./node_modules/ws/index.js 8:19-42
 @ ./node_modules/engine.io/build/server.js 12:13-26
 @ ./node_modules/engine.io/build/engine.io.js 5:17-36
 @ ./node_modules/socket.io/dist/index.js 36:20-40
 @ ./src/index.ts 15:20-40

**Comment by mmhzlrj** [comment]
![2](https://user-images.githubusercontent.com/29726050/236981810-e59cb038-565c-44b5-aff4-7d16dcfbd4bb.png)

**Comment by mmhzlrj** [comment]
~/freedom-gpt$ yarn start
yarn run v1.22.19
$ electron-forge start
✔ Checking your system
✔ Locating application
✔ Loading configuration
✔ Preparing native dependencies [0.4s]
✔ Running generateAssets hook
✔ [plugin-webpack] Compiling main process code [2s]
✔ [plugin-webpack] Launching dev servers for renderer process code [0.8s]
  › Output Available: http://localhost:9000

Server listening on port 8889
Failed to start child process: Error: spawn /home/jet/freedom-gpt/llama.cpp/main ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn /home/jet/freedom-gpt/llama.cpp/main',
  path: '/home/jet/freedom-gpt/llama.cpp/main',
  spawnargs: [ '-m', '/home/jet/freedom-gpt/model/ggml-alpaca-7b-q4.bin', '-ins' ]
}

**Comment by selzero** [comment]
Same issue here. 

"Child process exited with code 2 and signal null" in the command line. 
Loading Model stuck in the UI
"Module not found: Error: Can't resolve 'bufferutil'" stuck in the browser, as well as "Module not found: Error: Can't resolve 'utf-8-validate"



![image](https://github.com/ohmplatform/FreedomGPT/assets/2947865/2cadab87-68ff-4821-b590-3676520f5805)

**Comment by selzero** [comment]
Is the Linux environment not supported? It would be nice to know if this is the case.
